### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by uestla** [uestla/Sparse-Matrix#15]
1. **Matrix operations**
  - [ ] `operator[][]` (both getter and setter) - #12
  - [ ] `scalar * matrix`
  - [ ] `matrix / scalar`
  - [ ] transposition
  - [ ] values iteration using iterator class

2. **Optimizations**
  - [ ] M-M multiplication - see [this PDF](http://www.math.tamu.edu/~srobertp/Courses/Math639_2014_Sp/CRSDescription/CRSStuff.pdf), chapter 5 (site 14)
  - [ ] M-M addition and subtraction

3. **Other**
  - [x] add namespace - #9
  - [x] coding standards - #10
  - [ ] add benchmark to tests (speed of read/write of values and operations)
